name: Advent-of-Code-2k20
version: 0.1.0.0
github: "Rick-T/Advent-of-Code-2k20"
license: BSD3
author: "Patrick Teubner"
maintainer: "example@example.com"
copyright: "2020 Patrick Teubner"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Rick-T/Advent-of-Code-2k20#readme>

dependencies:
  - base >= 4.7 && < 5
  - timeit

library:
  source-dirs: src

data-files:
  - input/*/*.txt
  - input/*.txt

executables:
  Advent-of-Code-2k20-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Advent-of-Code-2k20

tests:
  Advent-of-Code-2k20-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Advent-of-Code-2k20
